name: algonlp CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - run: |
        nvm use 14
        npm i
        cd frontend
        npm i
        npm run build
